title: "shivam's blog"
description: >-
  i write here sometimes
baseurl: "/blog" # the subpath of your site
url: "https://yourusername.github.io" # replace with your GitHub username
permalink: /:year/:month/:day/:title/
theme: minima

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache/
